import ICustomer from "../types/customer";

export const Customer: ICustomer[] = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    phone: "555-1234",
    orders: 3,
    total_spent: 152.75,
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    phone: "555-5678",
    orders: 5,
    total_spent: 320.4,
  },
  {
    id: 3,
    name: "Carol Lee",
    email: "carol.lee@example.com",
    phone: "555-8765",
    orders: 2,
    total_spent: 89.99,
  },
  {
    id: 4,
    name: "David Kim",
    email: "david.kim@example.com",
    phone: "555-4321",
    orders: 7,
    total_spent: 540.2,
  },
  {
    id: 5,
    name: "Eva Green",
    email: "eva.green@example.com",
    phone: "555-2468",
    orders: 1,
    total_spent: 45.5,
  },
  {
    id: 6,
    name: "Frank Wright",
    email: "frank.wright@example.com",
    phone: "555-1357",
    orders: 4,
    total_spent: 210.1,
  },
  {
    id: 7,
    name: "Grace Liu",
    email: "grace.liu@example.com",
    phone: "555-9753",
    orders: 6,
    total_spent: 389.6,
  },
  {
    id: 8,
    name: "Henry Adams",
    email: "henry.adams@example.com",
    phone: "555-8642",
    orders: 3,
    total_spent: 150.0,
  },
  {
    id: 9,
    name: "Irene Thomas",
    email: "irene.thomas@example.com",
    phone: "555-2222",
    orders: 2,
    total_spent: 75.25,
  },
  {
    id: 10,
    name: "Jack Miller",
    email: "jack.miller@example.com",
    phone: "555-4444",
    orders: 8,
    total_spent: 612.3,
  },
];
